export enum PollStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  TIE = 'TIE',
}

export enum NotificationType {
  POLL_CREATED = 'POLL_CREATED',
  POLL_COMPLETE = 'POLL_COMPLETED',
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_SHARE_SETTLED = 'EXPENSE_SHARE_SETTLED',
  MEMBER_JOINED = 'MEMBER_JOINED',
}
