export enum PollStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  TIE = 'TIE',
}

export enum NotificationType {
  POLL_CREATED = 'POLL_CREATED',
  POLL_COMPLETE = 'POLL_COMPLETED',
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_SHARE_SETTLED = 'EXPENSE_SHARE_SETTLED',
  MEMBER_JOINED = 'MEMBER_JOINED',
}

export enum EventCategory {
  GENERAL = 'GENERAL',
  TRAVEL = 'TRAVEL',
  ACTIVITY = 'ACTIVITY',
  MEAL = 'MEAL',
  MEETING = 'MEETING',
  FREE_TIME = 'FREE_TIME',
  OTHER = 'OTHER',
}

export enum LocationType {
  ACCOMMODATION = 'ACCOMMODATION',
  RESTAURANT = 'RESTAURANT',
  CAFE = 'CAFE',
  SHOPPING = 'SHOPPING',
  GAS_STATION = 'GAS_STATION',
  OTHER = 'OTHER',
}
