export enum PollStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  TIE = 'TIE',
}

export enum NotificationType {
  POLL_CREATED = 'POLL_CREATED',
  POLL_COMPLETE = 'POLL_COMPLETED',
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_REMINDER = 'EVENT_REMINDER',
  EVENT_ASSIGNMENT = 'EVENT_ASSIGNMENT',
  EVENT_UNASSIGNMENT = 'EVENT_UNASSIGNMENT',
  EVENT_NOTE_ADDED = 'EVENT_NOTE_ADDED',
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_SHARE_ADDED = 'EXPENSE_SHARE_ADDED',
  EXPENSE_SHARE_SETTLED = 'EXPENSE_SHARE_SETTLED',
  LOCATION_MARKED = 'LOCATION_MARKED',
  INVITE_REJECTED = 'INVITE_REJECTED',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  MEMBERS_REMOVED = 'MEMBERS_REMOVED',
  MEMBER_ROLE_UPDATED = 'MEMBER_ROLE_UPDATED',
  TRIP_UPDATED = 'TRIP_UPDATED',
  TRIP_DELETED = 'TRIP_DELETED',
}

export enum EventCategory {
  GENERAL = 'GENERAL',
  TRAVEL = 'TRAVEL',
  ACTIVITY = 'ACTIVITY',
  MEAL = 'MEAL',
  MEETING = 'MEETING',
  FREE_TIME = 'FREE_TIME',
  OTHER = 'OTHER',
}

export enum LocationType {
  ACCOMMODATION = 'ACCOMMODATION',
  RESTAURANT = 'RESTAURANT',
  CAFE = 'CAFE',
  SHOPPING = 'SHOPPING',
  GAS_STATION = 'GAS_STATION',
  OTHER = 'OTHER',
}
