services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
      - ./server/.env.test
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: always

  server-loadtest:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    env_file:
      - ./server/.env.loadtest
    environment:
      DATABASE_URL: postgresql://vamoose:testpassword@loadtest-db:5432/vamoose_test
      DIRECT_URL: postgresql://vamoose:testpassword@loadtest-db:5432/vamoose_test
      MONGO_TEST_URI: mongodb://mongo:mongo@loadtest-mongodb:27017/tests?authSource=admin&directConnection=true
    depends_on:
      - loadtest-db
      - loadtest-mongodb
    restart: unless-stopped

  loadtest-db:
    image: postgres:15
    container_name: vamoose-loadtest-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: vamoose
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: vamoose_test
    volumes:
      - loadtest-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    tmpfs:
      - /var/lib/postgresql/data

  loadtest-mongodb:
    image: mongo:4.4
    container_name: vamoose-loadtest-mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: tests
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  loadtest-db-data: