name: Server CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [dev, uat, main]

jobs:
  server-test-lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run ESLint
        working-directory: server
        run: |
          docker compose up -d server
          docker exec server-ci npm run lint
          docker compose down

      - name: Run Unit Tests
        working-directory: server
        run: |
          docker compose up -d server
          docker exec server-ci npm run test:unit
          docker compose down

      - name: Run Integration Tests
        working-directory: server
        run: |
          docker compose up -d server
          docker exec server-ci npm run test:integration
          docker compose down

      - name: Verify Build
        working-directory: server
        run: |
          docker compose up -d server
          docker exec server-ci npm run build
          docker compose down
