name: Server CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [dev, uat, main]

jobs:
  server-test-lint-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Server Docker Image
        run: |
          docker build --no-cache -t server-ci -f server/Dockerfile ./server

      - name: Run ESLint in Docker
        run: docker run --rm server-ci npm run lint

      - name: Run Unit Tests in Docker
        run: docker run --rm server-ci npm run test:unit

      - name: Create Docker network for CI
        run: docker network create ci-network

      - name: Run Test Database Container
        run: |
          docker run -d \
            --name integration-tests-prisma \
            --network ci-network \
            -p 5433:5432 \
            -e POSTGRES_USER=prisma \
            -e POSTGRES_PASSWORD=prisma \
            -e POSTGRES_DB=tests \
            postgres:13

      - name: Run Integration Tests in Docker
        run: | 
          docker run --rm --network ci-network \
          -e DATABASE_URL="postgresql://prisma:prisma@integration-tests-prisma:5432/tests" \
          -e DIRECT_URL="postgresql://prisma:prisma@integration-tests-prisma:5432/tests" \
          server-ci npm run test:integration

      - name: Cleanup Test Database Container
        run: docker rm -f integration-tests-prisma

      - name: Remove Docker network
        run: docker network rm ci-network

      - name: Verify Build in Docker
        run: docker run --rm server-ci npm run build
