name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allow manual trigger on other branch to test
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }} \
            -t gcr.io/${{ secrets.GCP_PROJECT }}/vamoose-frontend:latest \
            -f frontend/Dockerfile frontend

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/vamoose-frontend:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: vamoose-frontend
          image: gcr.io/${{ secrets.GCP_PROJECT }}/vamoose-frontend:latest
          region: us-central1
          allow-unauthenticated: true
          timeout: 600s
