name: Push Frontend & Server to Docker Hub

on:
  push: # requirement in rubric is to do once a sprint, but we can have automatic since we dont merge to main often
    branches:
      - main
  workflow_dispatch:  # manual trigger also possible

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Server Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vamoose-server:latest ./server

      - name: Push Server to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vamoose-server:latest

      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }} \
            --build-arg NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/vamoose-frontend:latest ./frontend

      - name: Push Frontend to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vamoose-frontend:latest
